export TAP_EMAIL="nathan.garza@pinnacol.com"
export TAP_USER="garzan"
export TAP_USERNAME="Nathan Garza"
export EDITOR="vim"
export VISUAL="mate"
export GIT_EDITOR="vim"

# ORACLE_CLIENT_PATH=/usr/local/instantclient-10.2.0.4.0
# ORACLE_SDK_PATH=${ORACLE_CLIENT_PATH}/sdk/include
# export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$ORACLE_CLIENT_PATH:$ORACLE_SDK_PATH
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_CLIENT_PATH:$ORACLE_SDK_PATH
# export PATH=$PATH:$ORACLE_CLIENT_PATH
# export LIBRARY_PATH=$LIBRARY_PATH:$ORACLE_CLIENT_PATH:$ORACLE_SDK_PATH # Needed?
# export ORACLE_HOME=$ORACLE_CLIENT_PATH
# export SQLPATH=$HOME:$ORACLE_CLIENT_PATH
# export TNS_ADMIN=$ORACLE_CLIENT_PATH

ORACLE_CLIENT_PATH=/usr/local/instantclient-10.2.0.4.0
ORACLE_SDK_PATH=${ORACLE_CLIENT_PATH}/sdk/include
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$ORACLE_CLIENT_PATH:$ORACLE_SDK_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_CLIENT_PATH:$ORACLE_SDK_PATH
export PATH=/usr/local/bin:$PATH:$ORACLE_CLIENT_PATH:$HOME/toolbox/bin:$HOME/.rvm/bin
export LIBRARY_PATH=$LIBRARY_PATH:$ORACLE_CLIENT_PATH:$ORACLE_SDK_PATH # Needed?
export ORACLE_HOME=$ORACLE_CLIENT_PATH
export SQLPATH=$HOME:$ORACLE_CLIENT_PATH
export TNS_ADMIN=$ORACLE_CLIENT_PATH
# export PATH="$PATH:$HOME/toolbox/bin"
# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source $HOME/.bashrc
source $HOME/.bashrc2
